spring:
  application:
    name: routeplan
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/routeplan}
    username: ${SPRING_DATASOURCE_USERNAME:routeplan}
    password: ${SPRING_DATASOURCE_PASSWORD:routeplan-local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  shutdown: graceful
