springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: never
