springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never

management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,250ms,500ms,1s,2s,5s
