ALTER TABLE places
    ADD COLUMN environment VARCHAR(20) NOT NULL DEFAULT 'MIXED',
    ADD CONSTRAINT ck_places_environment CHECK (
        environment IN ('INDOOR', 'OUTDOOR', 'MIXED')
    );

CREATE TABLE trip_weather_forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    forecast_date DATE NOT NULL,
    condition VARCHAR(20) NOT NULL,
    precipitation_probability INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trip_weather_forecasts_trip
        FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT uk_trip_weather_forecasts_trip_date UNIQUE (trip_id, forecast_date),
    CONSTRAINT ck_trip_weather_forecasts_condition CHECK (
        condition IN ('CLEAR', 'CLOUDY', 'RAIN', 'SNOW', 'EXTREME')
    ),
    CONSTRAINT ck_trip_weather_forecasts_precipitation CHECK (
        precipitation_probability BETWEEN 0 AND 100
    )
);

CREATE INDEX idx_trip_weather_forecasts_trip_date
    ON trip_weather_forecasts (trip_id, forecast_date);

ALTER TABLE itinerary_days
    ADD COLUMN weather_condition VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN precipitation_probability INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_itinerary_days_weather_condition CHECK (
        weather_condition IN ('UNKNOWN', 'CLEAR', 'CLOUDY', 'RAIN', 'SNOW', 'EXTREME')
    ),
    ADD CONSTRAINT ck_itinerary_days_precipitation CHECK (
        precipitation_probability BETWEEN 0 AND 100
    );

ALTER TABLE itinerary_items
    ADD COLUMN weather_score_adjustment INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_itinerary_items_weather_adjustment CHECK (
        weather_score_adjustment BETWEEN -100 AND 100
    );
