CREATE TABLE trip_budget_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    spend_date DATE,
    category VARCHAR(30),
    limit_minor BIGINT NOT NULL CHECK (limit_minor BETWEEN 0 AND 1000000000000),
    CHECK (spend_date IS NOT NULL OR category IS NOT NULL),
    UNIQUE NULLS NOT DISTINCT(trip_id, spend_date, category)
);
CREATE TABLE trip_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    request_id UUID NOT NULL,
    spend_date DATE NOT NULL,
    category VARCHAR(30) NOT NULL,
    description VARCHAR(200) NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor BETWEEN 0 AND 1000000000000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(trip_id, request_id)
);
CREATE INDEX ix_trip_expenses_date ON trip_expenses(trip_id, spend_date);
CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    categories VARCHAR(300) NOT NULL DEFAULT '',
    regions TEXT NOT NULL DEFAULT '[]',
    pace VARCHAR(30),
    transport_mode VARCHAR(30)
);
CREATE TABLE route_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES shared_routes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    body VARCHAR(2000) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_route_comments_route ON route_comments(route_id, id DESC);
CREATE TABLE route_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES shared_routes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    body VARCHAR(2000) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(route_id, user_id)
);
CREATE TABLE community_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES shared_routes(id) ON DELETE CASCADE,
    reporter_id BIGINT NOT NULL REFERENCES users(id),
    target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('ROUTE','COMMENT','REVIEW')),
    target_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    detail VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','DISMISSED','ACTIONED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolved_by BIGINT REFERENCES users(id),
    UNIQUE(reporter_id, target_type, target_id)
);
ALTER TABLE shared_routes ADD COLUMN moderated_hidden BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX ix_community_reports_open ON community_reports(id) WHERE status='OPEN';
CREATE TABLE community_write_usage (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bucket_start TIMESTAMPTZ NOT NULL,
    units INTEGER NOT NULL CHECK(units BETWEEN 0 AND 30),
    PRIMARY KEY(user_id,bucket_start)
);
