CREATE TABLE wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100),
    city VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlists_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_wishlists_user_name UNIQUE (user_id, name)
);

CREATE INDEX idx_wishlists_user_updated ON wishlists (user_id, updated_at DESC);

CREATE TABLE wishlist_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_url VARCHAR(2048),
    memo VARCHAR(1000),
    estimated_cost_minor BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlist_places_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists (id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_places_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_wishlist_places_wishlist_place UNIQUE (wishlist_id, place_id),
    CONSTRAINT ck_wishlist_places_estimated_cost CHECK (estimated_cost_minor IS NULL OR estimated_cost_minor >= 0)
);

CREATE INDEX idx_wishlist_places_wishlist_created ON wishlist_places (wishlist_id, created_at);

CREATE TABLE content_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wishlist_id BIGINT,
    source_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    input_text VARCHAR(10000),
    detected_title VARCHAR(500),
    warning VARCHAR(1000),
    error_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_content_imports_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_content_imports_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists (id) ON DELETE SET NULL
);

CREATE INDEX idx_content_imports_user_created ON content_imports (user_id, created_at DESC);

CREATE TABLE content_import_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_import_id BIGINT NOT NULL,
    mention_order INTEGER NOT NULL,
    match_rank INTEGER NOT NULL,
    extracted_name VARCHAR(200) NOT NULL,
    external_place_id VARCHAR(200),
    matched_name VARCHAR(200),
    formatted_address VARCHAR(500),
    latitude NUMERIC(9, 6),
    longitude NUMERIC(10, 6),
    primary_type VARCHAR(100),
    provider VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_content_import_candidates_import FOREIGN KEY (content_import_id) REFERENCES content_imports (id) ON DELETE CASCADE,
    CONSTRAINT uk_content_import_candidate_rank UNIQUE (content_import_id, mention_order, match_rank),
    CONSTRAINT ck_content_import_mention_order CHECK (mention_order > 0),
    CONSTRAINT ck_content_import_match_rank CHECK (match_rank >= 0),
    CONSTRAINT ck_content_import_candidate_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_content_import_candidate_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_content_import_candidates_import_order
    ON content_import_candidates (content_import_id, mention_order, match_rank);
