CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_nickname UNIQUE (nickname)
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    accommodation_name VARCHAR(100) NOT NULL,
    accommodation_latitude NUMERIC(9, 6) NOT NULL,
    accommodation_longitude NUMERIC(10, 6) NOT NULL,
    transport_mode VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trips_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_trips_single_day CHECK (start_date = end_date),
    CONSTRAINT ck_trips_accommodation_latitude CHECK (accommodation_latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_trips_accommodation_longitude CHECK (accommodation_longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_trips_user_id ON trips (user_id);

CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_place_id VARCHAR(200),
    name VARCHAR(150) NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(10, 6) NOT NULL,
    category VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_places_external_place_id UNIQUE (external_place_id),
    CONSTRAINT ck_places_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_places_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE trip_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trip_places_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_places_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_trip_places_trip_place UNIQUE (trip_id, place_id)
);

CREATE INDEX idx_trip_places_trip_id ON trip_places (trip_id);

CREATE TABLE itineraries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    algorithm VARCHAR(40) NOT NULL,
    total_distance_meters BIGINT NOT NULL,
    estimated_travel_minutes INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_itineraries_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT uk_itineraries_trip_version UNIQUE (trip_id, version),
    CONSTRAINT ck_itineraries_version CHECK (version > 0),
    CONSTRAINT ck_itineraries_distance CHECK (total_distance_meters >= 0),
    CONSTRAINT ck_itineraries_travel_minutes CHECK (estimated_travel_minutes >= 0)
);

CREATE INDEX idx_itineraries_trip_version ON itineraries (trip_id, version DESC);

CREATE TABLE itinerary_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL,
    travel_distance_meters BIGINT NOT NULL,
    estimated_travel_minutes INTEGER NOT NULL,
    CONSTRAINT fk_itinerary_items_itinerary FOREIGN KEY (itinerary_id) REFERENCES itineraries (id) ON DELETE CASCADE,
    CONSTRAINT fk_itinerary_items_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_itinerary_items_itinerary_sequence UNIQUE (itinerary_id, sequence),
    CONSTRAINT ck_itinerary_items_sequence CHECK (sequence > 0),
    CONSTRAINT ck_itinerary_items_distance CHECK (travel_distance_meters >= 0),
    CONSTRAINT ck_itinerary_items_travel_minutes CHECK (estimated_travel_minutes >= 0)
);

CREATE INDEX idx_itinerary_items_itinerary_sequence
    ON itinerary_items (itinerary_id, sequence);
