CREATE TABLE trip_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('OWNER', 'EDITOR', 'VIEWER')),
    invited_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_trip_members_trip_user UNIQUE (trip_id, user_id)
);

CREATE INDEX ix_trip_members_user ON trip_members(user_id, joined_at DESC);

INSERT INTO trip_members(trip_id, user_id, role, invited_by, joined_at)
SELECT trip.id, trip.user_id, 'OWNER', trip.user_id, trip.created_at
FROM trips trip
ON CONFLICT (trip_id, user_id) DO NOTHING;

CREATE TABLE trip_place_votes (
    trip_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    value VARCHAR(10) NOT NULL CHECK (value IN ('YES', 'NO')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (trip_id, place_id, user_id),
    CONSTRAINT fk_trip_place_votes_place FOREIGN KEY (trip_id, place_id)
        REFERENCES trip_places(trip_id, place_id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_place_votes_member FOREIGN KEY (trip_id, user_id)
        REFERENCES trip_members(trip_id, user_id) ON DELETE CASCADE
);

CREATE INDEX ix_trip_place_votes_place ON trip_place_votes(trip_id, place_id);

ALTER TABLE trip_expenses
    ADD COLUMN payer_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN payer_nickname_snapshot VARCHAR(50);

UPDATE trip_expenses expense
SET payer_user_id = trip.user_id,
    created_by_user_id = trip.user_id,
    payer_nickname_snapshot = app_user.nickname
FROM trips trip
JOIN users app_user ON app_user.id = trip.user_id
WHERE trip.id = expense.trip_id;

ALTER TABLE trip_expenses
    ALTER COLUMN payer_nickname_snapshot SET NOT NULL;

CREATE TABLE trip_expense_participants (
    expense_id BIGINT NOT NULL REFERENCES trip_expenses(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    nickname_snapshot VARCHAR(50) NOT NULL,
    share_minor BIGINT NOT NULL CHECK (share_minor BETWEEN 0 AND 1000000000000),
    PRIMARY KEY (expense_id, user_id)
);

INSERT INTO trip_expense_participants(expense_id, user_id, nickname_snapshot, share_minor)
SELECT expense.id, trip.user_id, app_user.nickname, expense.amount_minor
FROM trip_expenses expense
JOIN trips trip ON trip.id = expense.trip_id
JOIN users app_user ON app_user.id = trip.user_id
ON CONFLICT (expense_id, user_id) DO NOTHING;

CREATE INDEX ix_trip_expense_participants_user ON trip_expense_participants(user_id, expense_id);
