ALTER TABLE shared_routes
    ADD COLUMN save_count BIGINT NOT NULL DEFAULT 0;

ALTER TABLE shared_routes
    DROP CONSTRAINT ck_shared_routes_counters,
    ADD CONSTRAINT ck_shared_routes_counters
        CHECK (view_count >= 0 AND copy_count >= 0 AND like_count >= 0 AND save_count >= 0);

CREATE TABLE route_saves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_route_id BIGINT NOT NULL REFERENCES shared_routes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_route_saves_route_user UNIQUE (shared_route_id, user_id)
);

CREATE INDEX idx_route_saves_user_created
    ON route_saves (user_id, created_at DESC, id DESC);
