ALTER TABLE trips
    ADD COLUMN daily_start_time TIME NOT NULL DEFAULT TIME '09:00',
    ADD COLUMN daily_end_time TIME NOT NULL DEFAULT TIME '20:00',
    ADD COLUMN pace VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    ADD CONSTRAINT ck_trips_daily_time CHECK (daily_end_time > daily_start_time);

ALTER TABLE places
    ADD COLUMN average_stay_minutes INTEGER NOT NULL DEFAULT 60,
    ADD CONSTRAINT ck_places_average_stay CHECK (average_stay_minutes BETWEEN 1 AND 1440);

CREATE TABLE place_opening_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL,
    CONSTRAINT fk_place_opening_hours_place
        FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE CASCADE,
    CONSTRAINT uk_place_opening_hours_place_day UNIQUE (place_id, day_of_week),
    CONSTRAINT ck_place_opening_hours_window CHECK (
        (closed = TRUE AND open_time IS NULL AND close_time IS NULL)
        OR
        (closed = FALSE AND open_time IS NOT NULL AND close_time IS NOT NULL AND close_time > open_time)
    )
);

CREATE INDEX idx_place_opening_hours_place_day
    ON place_opening_hours (place_id, day_of_week);

ALTER TABLE trip_places
    ADD COLUMN priority INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN must_visit BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN preferred_start_time TIME,
    ADD COLUMN preferred_end_time TIME,
    ADD COLUMN minimum_stay_minutes INTEGER,
    ADD COLUMN maximum_stay_minutes INTEGER,
    ADD CONSTRAINT ck_trip_places_priority CHECK (priority BETWEEN 1 AND 100),
    ADD CONSTRAINT ck_trip_places_preferred_window CHECK (
        preferred_start_time IS NULL
        OR preferred_end_time IS NULL
        OR preferred_end_time > preferred_start_time
    ),
    ADD CONSTRAINT ck_trip_places_minimum_stay CHECK (
        minimum_stay_minutes IS NULL OR minimum_stay_minutes BETWEEN 1 AND 1440
    ),
    ADD CONSTRAINT ck_trip_places_maximum_stay CHECK (
        maximum_stay_minutes IS NULL OR maximum_stay_minutes BETWEEN 1 AND 1440
    ),
    ADD CONSTRAINT ck_trip_places_stay_range CHECK (
        minimum_stay_minutes IS NULL
        OR maximum_stay_minutes IS NULL
        OR maximum_stay_minutes >= minimum_stay_minutes
    );

ALTER TABLE itineraries
    ADD COLUMN optimization_score INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN total_stay_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN total_waiting_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN return_travel_distance_meters BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN return_travel_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN returned_to_accommodation BOOLEAN NOT NULL DEFAULT FALSE,
    ADD CONSTRAINT ck_itineraries_score CHECK (optimization_score >= 0),
    ADD CONSTRAINT ck_itineraries_stay_minutes CHECK (total_stay_minutes >= 0),
    ADD CONSTRAINT ck_itineraries_waiting_minutes CHECK (total_waiting_minutes >= 0),
    ADD CONSTRAINT ck_itineraries_return_distance CHECK (return_travel_distance_meters >= 0),
    ADD CONSTRAINT ck_itineraries_return_minutes CHECK (return_travel_minutes >= 0);

ALTER TABLE itinerary_items
    ADD COLUMN visit_date DATE,
    ADD COLUMN arrival_time TIME,
    ADD COLUMN start_time TIME,
    ADD COLUMN end_time TIME,
    ADD COLUMN waiting_minutes INTEGER,
    ADD COLUMN stay_minutes INTEGER,
    ADD COLUMN priority INTEGER,
    ADD COLUMN must_visit BOOLEAN,
    ADD CONSTRAINT ck_itinerary_items_waiting_minutes CHECK (
        waiting_minutes IS NULL OR waiting_minutes >= 0
    ),
    ADD CONSTRAINT ck_itinerary_items_stay_minutes CHECK (
        stay_minutes IS NULL OR stay_minutes > 0
    ),
    ADD CONSTRAINT ck_itinerary_items_priority CHECK (
        priority IS NULL OR priority BETWEEN 1 AND 100
    ),
    ADD CONSTRAINT ck_itinerary_items_visit_times CHECK (
        start_time IS NULL OR end_time IS NULL OR end_time > start_time
    );

CREATE TABLE itinerary_exclusions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    priority INTEGER NOT NULL,
    reason VARCHAR(40) NOT NULL,
    CONSTRAINT fk_itinerary_exclusions_itinerary
        FOREIGN KEY (itinerary_id) REFERENCES itineraries (id) ON DELETE CASCADE,
    CONSTRAINT fk_itinerary_exclusions_place
        FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_itinerary_exclusions_itinerary_place UNIQUE (itinerary_id, place_id),
    CONSTRAINT ck_itinerary_exclusions_priority CHECK (priority BETWEEN 1 AND 100)
);

CREATE INDEX idx_itinerary_exclusions_itinerary
    ON itinerary_exclusions (itinerary_id);
