CREATE TABLE shared_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_trip_id BIGINT,
    source_itinerary_id BIGINT,
    source_itinerary_version INTEGER NOT NULL,
    source_trip_name VARCHAR(100) NOT NULL,
    source_start_date DATE NOT NULL,
    daily_start_time TIME NOT NULL,
    daily_end_time TIME NOT NULL,
    accommodation_name VARCHAR(100) NOT NULL,
    accommodation_latitude NUMERIC(9, 6) NOT NULL,
    accommodation_longitude NUMERIC(10, 6) NOT NULL,
    transport_mode VARCHAR(30) NOT NULL,
    pace VARCHAR(20) NOT NULL,
    algorithm VARCHAR(40) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    region VARCHAR(100) NOT NULL,
    travel_days INTEGER NOT NULL,
    visibility VARCHAR(20) NOT NULL,
    place_count INTEGER NOT NULL,
    place_preview VARCHAR(500) NOT NULL,
    total_distance_meters BIGINT NOT NULL,
    estimated_travel_minutes INTEGER NOT NULL,
    optimization_score INTEGER NOT NULL,
    view_count BIGINT NOT NULL DEFAULT 0,
    copy_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shared_routes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_shared_routes_source_trip
        FOREIGN KEY (source_trip_id) REFERENCES trips (id) ON DELETE SET NULL,
    CONSTRAINT fk_shared_routes_source_itinerary
        FOREIGN KEY (source_itinerary_id) REFERENCES itineraries (id) ON DELETE SET NULL,
    CONSTRAINT uk_shared_routes_source_itinerary UNIQUE (source_itinerary_id),
    CONSTRAINT ck_shared_routes_source_version CHECK (source_itinerary_version > 0),
    CONSTRAINT ck_shared_routes_daily_time CHECK (daily_end_time > daily_start_time),
    CONSTRAINT ck_shared_routes_accommodation_latitude
        CHECK (accommodation_latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_shared_routes_accommodation_longitude
        CHECK (accommodation_longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_shared_routes_travel_days CHECK (travel_days > 0),
    CONSTRAINT ck_shared_routes_visibility CHECK (visibility IN ('PUBLIC', 'UNLISTED')),
    CONSTRAINT ck_shared_routes_place_count CHECK (place_count > 0),
    CONSTRAINT ck_shared_routes_distance CHECK (total_distance_meters >= 0),
    CONSTRAINT ck_shared_routes_travel_minutes CHECK (estimated_travel_minutes >= 0),
    CONSTRAINT ck_shared_routes_score CHECK (optimization_score >= 0),
    CONSTRAINT ck_shared_routes_counters
        CHECK (view_count >= 0 AND copy_count >= 0 AND like_count >= 0)
);

CREATE INDEX idx_shared_routes_discovery
    ON shared_routes (visibility, published_at DESC);

CREATE INDEX idx_shared_routes_region_days
    ON shared_routes (region, travel_days);

CREATE INDEX idx_shared_routes_popularity
    ON shared_routes (visibility, copy_count DESC, like_count DESC, view_count DESC);

CREATE TABLE shared_route_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_route_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    day_number INTEGER NOT NULL,
    sequence INTEGER NOT NULL,
    visit_date DATE NOT NULL,
    place_name VARCHAR(150) NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(10, 6) NOT NULL,
    category VARCHAR(50),
    arrival_time TIME NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    travel_distance_meters BIGINT NOT NULL,
    estimated_travel_minutes INTEGER NOT NULL,
    waiting_minutes INTEGER NOT NULL,
    stay_minutes INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    must_visit BOOLEAN NOT NULL,
    CONSTRAINT fk_shared_route_items_route
        FOREIGN KEY (shared_route_id) REFERENCES shared_routes (id) ON DELETE CASCADE,
    CONSTRAINT fk_shared_route_items_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_shared_route_items_route_sequence UNIQUE (shared_route_id, sequence),
    CONSTRAINT ck_shared_route_items_day CHECK (day_number > 0),
    CONSTRAINT ck_shared_route_items_sequence CHECK (sequence > 0),
    CONSTRAINT ck_shared_route_items_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_shared_route_items_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_shared_route_items_time CHECK (end_time > start_time),
    CONSTRAINT ck_shared_route_items_distance CHECK (travel_distance_meters >= 0),
    CONSTRAINT ck_shared_route_items_travel_minutes CHECK (estimated_travel_minutes >= 0),
    CONSTRAINT ck_shared_route_items_waiting_minutes CHECK (waiting_minutes >= 0),
    CONSTRAINT ck_shared_route_items_stay_minutes CHECK (stay_minutes > 0),
    CONSTRAINT ck_shared_route_items_priority CHECK (priority BETWEEN 1 AND 100)
);

CREATE INDEX idx_shared_route_items_route_sequence
    ON shared_route_items (shared_route_id, sequence);

CREATE TABLE route_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_route_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_route_likes_route
        FOREIGN KEY (shared_route_id) REFERENCES shared_routes (id) ON DELETE CASCADE,
    CONSTRAINT fk_route_likes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_route_likes_route_user UNIQUE (shared_route_id, user_id)
);

CREATE INDEX idx_route_likes_user_id ON route_likes (user_id);
