ALTER TABLE trips
    DROP CONSTRAINT ck_trips_single_day,
    ADD CONSTRAINT ck_trips_date_range CHECK (
        end_date >= start_date AND end_date <= start_date + 13
    );

CREATE TABLE itinerary_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id BIGINT NOT NULL,
    visit_date DATE NOT NULL,
    day_number INTEGER NOT NULL,
    total_distance_meters BIGINT NOT NULL,
    estimated_travel_minutes INTEGER NOT NULL,
    total_stay_minutes INTEGER NOT NULL,
    total_waiting_minutes INTEGER NOT NULL,
    return_travel_distance_meters BIGINT NOT NULL,
    return_travel_minutes INTEGER NOT NULL,
    return_arrival_time TIME NOT NULL,
    returned_to_accommodation BOOLEAN NOT NULL,
    CONSTRAINT fk_itinerary_days_itinerary
        FOREIGN KEY (itinerary_id) REFERENCES itineraries (id) ON DELETE CASCADE,
    CONSTRAINT uk_itinerary_days_itinerary_date UNIQUE (itinerary_id, visit_date),
    CONSTRAINT uk_itinerary_days_itinerary_number UNIQUE (itinerary_id, day_number),
    CONSTRAINT ck_itinerary_days_number CHECK (day_number > 0),
    CONSTRAINT ck_itinerary_days_distance CHECK (total_distance_meters >= 0),
    CONSTRAINT ck_itinerary_days_travel_minutes CHECK (estimated_travel_minutes >= 0),
    CONSTRAINT ck_itinerary_days_stay_minutes CHECK (total_stay_minutes >= 0),
    CONSTRAINT ck_itinerary_days_waiting_minutes CHECK (total_waiting_minutes >= 0),
    CONSTRAINT ck_itinerary_days_return_distance CHECK (return_travel_distance_meters >= 0),
    CONSTRAINT ck_itinerary_days_return_minutes CHECK (return_travel_minutes >= 0)
);

CREATE INDEX idx_itinerary_days_itinerary_number
    ON itinerary_days (itinerary_id, day_number);
